### ISSUE TITLE
systools 在 0 byte 的文件 (被清空的情況) 下依然備份，導致舊文件被覆蓋

### ISSUE THREAD

**Issue by eric2788** [zhuhansan666/koishi-plugin-systools#2]
建議新增 0 byte 時略過備份，以保留正常的備份檔案防止一直備份空文件導致被覆蓋

**Comment by eric2788** [comment]
另外有一個問題不知道是否systool導致，現在我的package.json被清空了

**Comment by CyanChanges** [comment]
> 另外有一個問題不知道是否systool導致，現在我的package.json被清空了

是会有这种情况的，之前我整 k2sec 狂写 pkg.json 的时候就炸过

**Comment by lovemilk2333** [comment]
> 另外有一個問題不知道是否systool導致，現在我的package.json被清空了另外有一个问题不知道是否systool导致，现在我的package.json被清空了

您好, 请问是 根目录的 `package.json` 还是插件的?

**Comment by lovemilk2333** [comment]
您好, 跳过空文件功能已实现.
请您尽快升级至 >= Systools V1.2.13 (Systools-lts V0.0.7)
感谢您的支持~ :)

**Comment by eric2788** [comment]
> 您好, 跳过空文件功能已实现. 请您尽快升级至 >= Systools V1.2.13 (Systools-lts V0.0.7) 感谢您的支持~ :)

很久沒用koishi了，不過實現了可以直接関issue了，感謝
